In [1]:
#create the array 

import numpy as np
arr=np.array([10,20,30,405,50],dtype=float)
arr

array([ 10.,  20.,  30., 405.,  50.])

In [17]:
#2d
arr_2=np.random.randint(10,size=(3,4,))
arr_2


array([[6, 7, 5, 8],
       [8, 2, 1, 7],
       [2, 3, 7, 3]], dtype=int32)

In [3]:
#3d
arr_3=np.random.randint(20,size=(3,4,5))
arr_3


array([[[17, 11, 15,  6,  7],
        [12, 10, 14,  4, 15],
        [ 4,  2, 13, 17,  4],
        [ 9,  3,  1, 16,  8]],

       [[ 4,  0,  8,  4, 16],
        [19, 19, 13, 13,  7],
        [ 5,  6,  6, 18, 19],
        [ 4, 10, 15,  9,  9]],

       [[ 0, 13,  1,  7,  5],
        [ 3,  3, 16,  2, 15],
        [ 8,  5, 10,  0,  1],
        [ 3,  1,  8,  4, 19]]], dtype=int32)

In [4]:
arr_4=np.random.seed(40)
print(arr_4)

None


In [5]:
arr_3=np.full((3,5),3.14)
arr_3

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
#stepping 2
arr_3=np.arange(0,20,2 )
arr_3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr_3=np.linspace(0,5)
arr_3


array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [8]:
str="shrinath"
str


'shrinath'

In [9]:
#first index
str[0]

's'

In [10]:
#last index
str[-1]

'h'

In [11]:
#second last
str[-2]

't'

In [12]:
#slicing
str1=10,20,30,40,50,60,70,80,90,100,110,120
print(str1[:5])

(10, 20, 30, 40, 50)


In [13]:
print(str1[6:])

(70, 80, 90, 100, 110, 120)


In [14]:
print(str1[:-5])

(10, 20, 30, 40, 50, 60, 70)


In [15]:
#aggregation function

print("sum",np.sum(arr_3))
print("mean",np.mean(arr_3))
print("median",np.median(arr_3))
print("minimum",np.min(arr_3))
print("maximun",np.max(arr_3))
print("standard derivation",np.std(arr_3))

sum 125.0
mean 2.5
median 2.5
minimum 0.0
maximun 5.0
standard derivation 1.4725377234348789


In [16]:
#universal  function

print("square root",np.sqrt(arr_3))
print("square",np.square(arr_3))
print("exponential",np.exp(arr_3))


square root [0.         0.31943828 0.45175395 0.55328334 0.63887656 0.71428571
 0.7824608  0.84515425 0.9035079  0.95831485 1.01015254 1.05945693
 1.10656667 1.15175111 1.19522861 1.23717915 1.27775313 1.31707778
 1.35526185 1.39239919 1.42857143 1.46385011 1.49829835 1.53197218
 1.56492159 1.59719141 1.62882204 1.65985001 1.69030851 1.7202278
 1.74963553 1.77855709 1.80701581 1.83503323 1.86262926 1.88982237
 1.91662969 1.94306722 1.96914982 1.99489143 2.02030509 2.04540301
 2.07019668 2.0946969  2.11891385 2.14285714 2.16653584 2.18995853
 2.21313334 2.23606798]
square [0.00000000e+00 1.04123282e-02 4.16493128e-02 9.37109538e-02
 1.66597251e-01 2.60308205e-01 3.74843815e-01 5.10204082e-01
 6.66389005e-01 8.43398584e-01 1.04123282e+00 1.25989171e+00
 1.49937526e+00 1.75968347e+00 2.04081633e+00 2.34277384e+00
 2.66555602e+00 3.00916285e+00 3.37359434e+00 3.75885048e+00
 4.16493128e+00 4.59183673e+00 5.03956685e+00 5.50812162e+00
 5.99750104e+00 6.50770512e+00 7.03873386e+00 7.59058726