In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
data = load_iris()

X = data.data      # Features
y = data.target    # Labels

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (150, 4)
Target shape: (150,)


In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [4]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
model = keras.Sequential([
    keras.layers.Dense(16, activation='relu', input_shape=(4,)),
    keras.layers.Dense(12, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

In [6]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [7]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    validation_split=0.1
)

Epoch 1/50


4/4 [==============================] - 2s 115ms/step - loss: 1.1052 - accuracy: 0.3519 - val_loss: 1.1233 - val_accuracy: 0.1667
Epoch 2/50
4/4 [==============================] - 0s 23ms/step - loss: 1.0691 - accuracy: 0.3611 - val_loss: 1.0951 - val_accuracy: 0.1667
Epoch 3/50
4/4 [==============================] - 0s 17ms/step - loss: 1.0366 - accuracy: 0.3796 - val_loss: 1.0703 - val_accuracy: 0.1667
Epoch 4/50
4/4 [==============================] - 0s 19ms/step - loss: 1.0065 - accuracy: 0.3889 - val_loss: 1.0482 - val_accuracy: 0.2500
Epoch 5/50
4/4 [==============================] - 0s 19ms/step - loss: 0.9784 - accuracy: 0.3981 - val_loss: 1.0285 - val_accuracy: 0.2500
Epoch 6/50
4/4 [==============================] - 0s 27ms/step - loss: 0.9522 - accuracy: 0.4259 - val_loss: 1.0104 - val_accuracy: 0.4167
Epoch 7/50
4/4 [==============================] - 0s 29ms/step - loss: 0.9275 - accuracy: 0.4630 - val_loss: 0.9936 - val_accuracy: 0.4167
Epoch 8/50
4/4 [========

In [8]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Accuracy:", accuracy)

1/1 [==============================] - 0s 41ms/step - loss: 0.3122 - accuracy: 0.8667
Test Accuracy: 0.8666666746139526


In [9]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)

print(confusion_matrix(y_test, y_pred_classes))
print(classification_report(y_test, y_pred_classes))

1/1 [==============================] - 0s 116ms/step
[[10  0  0]
 [ 0  5  4]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.56      0.71         9
           2       0.73      1.00      0.85        11

    accuracy                           0.87        30
   macro avg       0.91      0.85      0.85        30
weighted avg       0.90      0.87      0.86        30



In [10]:
sample = X_test[0].reshape(1, -1)

prediction = model.predict(sample)
predicted_class = np.argmax(prediction)

print("Predicted Class:", predicted_class)
print("Actual Class:", y_test[0])

1/1 [==============================] - 0s 28ms/step
Predicted Class: 1
Actual Class: 1
