In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('placement.csv')

In [3]:
df

,Unnamed: 0,cgpa,iq,placement
0,0,6.8,123.0,1
1,1,5.9,106.0,0
2,2,5.3,121.0,0
3,3,7.4,132.0,1
4,4,5.8,142.0,0
...,...,...,...,...
95,95,4.3,200.0,0
96,96,4.4,42.0,0
97,97,6.7,182.0,1
98,98,6.3,103.0,1


In [4]:
df.head

<bound method NDFrame.head of     Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]>

In [5]:
df.tail

<bound method NDFrame.tail of     Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]>

In [8]:
#missing value
print(df.isnull().sum())

Unnamed: 0    0
cgpa          0
iq            0
placement     0
dtype: int64


In [9]:
#drop with missing value
print(df.dropna)

<bound method DataFrame.dropna of     Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]>


In [10]:
#fill the missing value with a specific value
mean_value=df['iq'].mean()
df['iq'].fillna(mean_value,inplace=True)


C:\Users\rajpu\AppData\Local\Temp\ipykernel_28428\4154368091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['iq'].fillna(mean_value,inplace=True)


In [11]:
df=pd.DataFrame(df)

In [12]:
print(df)

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]


In [13]:
#Conversion to the Tensor format

import numpy as np
import tensorflow as tf

In [16]:
X=df[['cgpa','placement']].values
y=df['iq'].values

In [17]:
X

array([[6.8, 1. ],
       [5.9, 0. ],
       [5.3, 0. ],
       [7.4, 1. ],
       [5.8, 0. ],
       [7.1, 1. ],
       [5.7, 0. ],
       [5. , 0. ],
       [6.1, 0. ],
       [5.1, 0. ],
       [6. , 1. ],
       [6.9, 1. ],
       [5.4, 0. ],
       [6.4, 1. ],
       [6.1, 0. ],
       [5.1, 0. ],
       [5.2, 0. ],
       [3.3, 0. ],
       [4. , 0. ],
       [5.2, 0. ],
       [6.6, 1. ],
       [7.1, 1. ],
       [4.9, 0. ],
       [4.7, 0. ],
       [4.7, 0. ],
       [5. , 0. ],
       [7. , 1. ],
       [6. , 1. ],
       [5.2, 0. ],
       [7. , 1. ],
       [7.6, 1. ],
       [3.9, 0. ],
       [7. , 1. ],
       [6. , 0. ],
       [4.8, 0. ],
       [6.8, 1. ],
       [5.7, 0. ],
       [8.1, 1. ],
       [6.5, 1. ],
       [4.6, 0. ],
       [4.9, 0. ],
       [5.4, 0. ],
       [7.6, 1. ],
       [6.8, 1. ],
       [7.5, 1. ],
       [6. , 1. ],
       [5.3, 0. ],
       [5.2, 0. ],
       [6.6, 1. ],
       [5.4, 0. ],
       [3.5, 0. ],
       [4.8, 0. ],
       [7. ,

In [18]:
y

array([123., 106., 121., 132., 142.,  48., 143.,  63., 156.,  66.,  45.,
       138., 139., 116., 103., 176., 224., 183., 100., 132., 120., 151.,
       120.,  87., 121.,  91., 199., 124.,  90., 112., 128., 109., 139.,
       149., 163.,  90., 140., 149., 160., 146., 134., 114.,  89., 141.,
        61.,  66., 114., 161., 138., 135., 233., 141., 175., 168., 141.,
       114.,  65., 130.,  79., 112., 139., 137., 102., 128.,  64., 166.,
        96., 118.,  75., 120., 127., 132., 116.,  61., 154., 169., 155.,
        50.,  81.,  90., 196., 107.,  37., 130., 169., 166., 128., 132.,
       149., 151.,  86., 158., 110., 112.,  52., 200.,  42., 182., 103.,
       113.])

In [19]:
#convert to tensorflow tensor 
X_tensor=tf.constant(X,dtype=tf.float32)
y_tensor=tf.constant(y,dtype=tf.int32)

In [20]:
#Alternatively you can use numpy array directly as Tensorflow

X_tensor=tf.convert_to_tensor(X,dtype=tf.float32)
y_tensor=tf.convert_to_tensor(y,dtype=tf.int32)

In [ ]:
print("\n X tensor \n",X_tensor)



 X tensor 
 tf.Tensor(
[[6.8 1. ]
 [5.9 0. ]
 [5.3 0. ]
 [7.4 1. ]
 [5.8 0. ]
 [7.1 1. ]
 [5.7 0. ]
 [5.  0. ]
 [6.1 0. ]
 [5.1 0. ]
 [6.  1. ]
 [6.9 1. ]
 [5.4 0. ]
 [6.4 1. ]
 [6.1 0. ]
 [5.1 0. ]
 [5.2 0. ]
 [3.3 0. ]
 [4.  0. ]
 [5.2 0. ]
 [6.6 1. ]
 [7.1 1. ]
 [4.9 0. ]
 [4.7 0. ]
 [4.7 0. ]
 [5.  0. ]
 [7.  1. ]
 [6.  1. ]
 [5.2 0. ]
 [7.  1. ]
 [7.6 1. ]
 [3.9 0. ]
 [7.  1. ]
 [6.  0. ]
 [4.8 0. ]
 [6.8 1. ]
 [5.7 0. ]
 [8.1 1. ]
 [6.5 1. ]
 [4.6 0. ]
 [4.9 0. ]
 [5.4 0. ]
 [7.6 1. ]
 [6.8 1. ]
 [7.5 1. ]
 [6.  1. ]
 [5.3 0. ]
 [5.2 0. ]
 [6.6 1. ]
 [5.4 0. ]
 [3.5 0. ]
 [4.8 0. ]
 [7.  1. ]
 [8.3 1. ]
 [6.4 1. ]
 [7.8 1. ]
 [6.1 0. ]
 [6.5 1. ]
 [8.  1. ]
 [4.8 0. ]
 [6.9 1. ]
 [7.3 1. ]
 [6.  0. ]
 [6.3 1. ]
 [7.  1. ]
 [8.1 1. ]
 [6.9 1. ]
 [5.  0. ]
 [4.  0. ]
 [8.5 1. ]
 [6.3 1. ]
 [6.1 1. ]
 [7.3 1. ]
 [4.9 0. ]
 [6.7 1. ]
 [4.8 0. ]
 [4.9 0. ]
 [7.3 1. ]
 [6.1 0. ]
 [6.5 1. ]
 [4.9 0. ]
 [5.4 0. ]
 [6.5 1. ]
 [7.5 1. ]
 [5.7 0. ]
 [5.8 1. ]
 [5.1 0. ]
 [5.7 1. ]
 [4.4 0.

In [22]:
print("\n Y Tensor \n",y_tensor)


 Y Tensor 
 tf.Tensor(
[123 106 121 132 142  48 143  63 156  66  45 138 139 116 103 176 224 183
 100 132 120 151 120  87 121  91 199 124  90 112 128 109 139 149 163  90
 140 149 160 146 134 114  89 141  61  66 114 161 138 135 233 141 175 168
 141 114  65 130  79 112 139 137 102 128  64 166  96 118  75 120 127 132
 116  61 154 169 155  50  81  90 196 107  37 130 169 166 128 132 149 151
  86 158 110 112  52 200  42 182 103 113], shape=(100,), dtype=int32)
